<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>f15f3e7b-4821-41be-9c12-38f93847788a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PortfolioIntelligencePlatform.Application\PortfolioIntelligencePlatform.Application.csproj" />
      <ProjectReference Include="..\PortfolioIntelligencePlatform.Infrastructure\PortfolioIntelligencePlatform.Infrastructure.csproj" />
    </ItemGroup>

</Project>
